name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
      - fix/**
  pull_request:
    branches:
      - main
      - dev

jobs:

  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Firefox
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Install geckodriver
        run: |
          sudo apt-get install -y firefox-geckodriver || true


      - name: Set geckodriver path
        run: echo "GECKODRIVER=$(which geckodriver)" >> $GITHUB_ENV